___

<a href='https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Running%20Code.html'> <img src='https://www.python.org/static/img/python-logo.png' /></a>
___

# NumPy Indexado y Selección

En esta lección veremos cómo seleccionar elementos o grupos de elementos de una matriz.

In [ ]:
import numpy as np

In [ ]:
#Creando una matriz de muestra
arr = np.arange(0,11)

In [ ]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Selección e indexación de soportes
La forma más sencilla de elegir uno o algunos elementos de una matriz es muy similar a las listas de Python:

In [ ]:
#Obtenga un valor en un índice
arr[8]

8

In [ ]:
#Obtener valores en un rango
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
#Obtener valores en un rango
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Las matrices Numpy difieren de una lista de Python normal debido a su capacidad para transmitir:

In [ ]:
#Establecer un valor con rango de índice (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
# Restablecer matriz, veremos por qué se tuvo que restablecer en un momento
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Notas importantes sobre Slices
slice_of_arr = arr[0:6]

#Mostrar slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Cambiar Slice
slice_of_arr[:]=99

#Mostrar Slice nuevamente
slice_of_arr

array([99, 99, 99, 99, 99, 99])

¡Ahora tener en cuenta que los cambios también ocurren en nuestra matriz original!

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Los datos no se copian, es una vista de la matriz original. ¡Esto evita problemas de memoria!

In [ ]:
#Para obtener una copia, debe ser explícito
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexando un array a 2D  (matrices)

La forma general es **arr_2d[row][col]** o **arr_2d[row,col]**. Por lo general, recomiendo usar la notación de coma para mayor claridad.

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexando fila
arr_2d[1]


array([20, 25, 30])

In [ ]:
# Formaato es arr_2d[row][col] o arr_2d[row,col]

# Obtener valor de elemento individual
arr_2d[1][0]

20

In [ ]:
# 2D array slicing

#Forma (2,2) desde la esquina superior derecha
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Forma fila inferior
arr_2d[2]

array([35, 40, 45])

In [ ]:
#Forma fila inferior
arr_2d[2,:]

array([35, 40, 45])

### Indexacion Elegante

La indexación elegante le permite seleccionar filas o columnas enteras fuera de orden, para mostrar esto, construyamos rápidamente una matriz numpy:

In [ ]:
#Construimos una matriz
arr2d = np.zeros((10,10))

In [ ]:
#Longitud de la matriz
arr_length = arr2d.shape[1]

In [ ]:
#Configurar matriz

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

La indexación elegante permite lo siguiente

In [ ]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
#Permite en cualquier orden
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selección

Repasemos brevemente cómo usar los corchetes para la selección basada en operadores de comparación.

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Great Job!
